using ClercSystem.Authorisation;
using ClercSystem.Data;
using ClercSystem.Data.Models;
using ClercSystem.Data.Seeder;
using ClercSystem.Infrastructure.Implementations;
using ClercSystem.Infrastructure.Interfaces;
using ClercSystem.Services.Implementations;
using ClercSystem.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClercSystem
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);
            
            builder.Services.AddApplicationDatabase(builder.Configuration); // adding db connection string with a method 
            builder.Services.AddApplicationServices(builder.Configuration); // add app services, app repositories included to the app
            builder.Services.AddApplicationIdentityServices(builder.Configuration); // add Identity Services to the app


            // 
            builder.Services.AddRazorPages();

            // Add the custom authorization policies
            builder.Services.AddAppAuthorization();

            // Add services to the container.
            builder.Services.AddControllersWithViews(options =>
            {
                options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute()); // automatically validates antiforgery tokens generated by post methods
            });

            var app = builder.Build();

            using (var scope = app.Services.CreateScope())
            {
                var services = scope.ServiceProvider;
                await AppDbSeeder.SeedDepartmentsAsync(services); // seed departments
                await AppDbSeeder.SeedCategoriesAsync(services); // seed categories
                await RolesSeeder.SeedRolesAsync(services);

                var departmentServie = services.GetRequiredService<IDepartmentService>();
                bool doesDepartmentExist = await departmentServie.DepartmentExistsAsync("Management", "Sofia");

                if (doesDepartmentExist) // Only seed the admin user if the "Management" department in "Sofia" exists, otherwise skip seeding the admin user to avoid potential issues with missing department reference.
                {
                    Guid departmentId = (await departmentServie.GetAllDepartmentsAsync())
                        .FirstOrDefault(d => d.Name == "Management" && d.Location == "Sofia").DepartmentId;

                    await UsersSeeder.SeedAdminDefaultUsersAsync(services, departmentId); // seed admin user
                }
            }

            var envi = app.Environment.EnvironmentName;
         
            // Configure the HTTP request pipeline.
            if (app.Environment.IsDevelopment())
            {
                app.UseExceptionHandler("/Error/500");
                app.UseStatusCodePagesWithReExecute("/Error/{0}");


                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();

            app.Use((context, next) =>
            {

                if (context.User.Identity?.IsAuthenticated == true && context.Request.Path == "/") // If the user is authenticated and trying to access the root URL
                {
                    if (context.User.IsInRole("Admin"))
                    {
                        context.Response.Redirect("/Admin/UserManagement/Index");
                        return Task.CompletedTask;
                    }
                }
                return next();
            });

            app.UseAuthorization();

            app.MapRazorPages();
            app.MapControllers();

            app.MapStaticAssets();

            // For the admin area routing code
            app.MapControllerRoute(
                name: "areas",
                pattern: "{area:exists}/{controller=UserManagement}/{action=Index}/{id?}");

            app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");
                

            app.Run();
        }
    }
}
